# Generated by Django 5.2.8 on 2026-07-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('phone', models.CharField(max_length=50, verbose_name='رقم الهاتف')),
                ('project', models.CharField(blank=True, max_length=255, null=True, verbose_name='المشروع')),
                ('unit', models.CharField(blank=True, max_length=255, null=True, verbose_name='الوحدة المهتم بها')),
                ('source', models.CharField(blank=True, max_length=255, null=True, verbose_name='المصدر / مكان التسجيل')),
                ('page', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان الصفحة')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='رابط الصفحة')),
                ('device', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع الجهاز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
            ],
            options={
                'verbose_name': 'طلب تسجيل (Lead)',
                'verbose_name_plural': 'طلبات التسجيل (Leads)',
                'ordering': ['-created_at'],
            },
        ),
    ]
