# Generated by Django 5.2.8 on 2026-07-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='تفاصيل الاهتمام والملاحظات'),
        ),
    ]
